var config = [

/****************************************** 		level 1 ----------- animals 		******************************************/
{level:"1", theme: "animals", question: "What is JavaScript?", answers: ["client-side scripting language", "son of java", "father of python", "language"], correct: 1},
{level:"1", theme: "animals", question: "What is the purpose of minifying the JavaScript?", answers: ["To streamline the visits", "To save the visits", "Both a and b", "None of the mentioned"], correct: 1},
{level:"1", theme: "animals", question: "From which did Minification concept originate?", answers: ["JavaScript code efficiency", "JavaScript interpreter", "Both a and b", "None of the mentioned"], correct: 2},
{level:"1", theme: "animals", question: "What is the purpose of the product Minify?", answers: ["Storing the data", "Streamlining the data", "Proxies the JavaScript file", "All of the mentioned"], correct: 3},
{level:"1", theme: "animals", question: "What does the Minify set the encoding HTTP header?", answers: ["deflate", "gzip", "Both a and b", "None of the mentioned"], correct: 3},
{level:"1", theme: "animals", question: "What is in-built in the Minify?", answers: ["Dynamic compression", "Static compression", "Static content", "None of the mentioned"], correct: 2},
{level:"1", theme: "animals", question: "YUI Compressor is analogous to", answers: ["Minify", "JavaScript", "Both a and b", "None of the mentioned"], correct: 1},
/****************************************** 		level 2 ----------- animals 		******************************************/
{level:"2", theme: "animals", question: "What is JavaScript?", answers: ["client-side scripting language", "son of java", "father of python", "language"], correct: 1},
{level:"2", theme: "animals", question: "What is the purpose of minifying the JavaScript?", answers: ["To streamline the visits", "To save the visits", "Both a and b", "None of the mentioned"], correct: 1},
{level:"2", theme: "animals", question: "From which did Minification concept originate?", answers: ["JavaScript code efficiency", "JavaScript interpreter", "Both a and b", "None of the mentioned"], correct: 2},
{level:"2", theme: "animals", question: "What is the purpose of the product Minify?", answers: ["Storing the data", "Streamlining the data", "Proxies the JavaScript file", "All of the mentioned"], correct: 3},
{level:"2", theme: "animals", question: "What does the Minify set the encoding HTTP header?", answers: ["deflate", "gzip", "Both a and b", "None of the mentioned"], correct: 3},
{level:"2", theme: "animals", question: "What is in-built in the Minify?", answers: ["Dynamic compression", "Static compression", "Static content", "None of the mentioned"], correct: 2},
{level:"2", theme: "animals", question: "YUI Compressor is analogous to", answers: ["Minify", "JavaScript", "Both a and b", "None of the mentioned"], correct: 1},
/****************************************** 		level 3 ----------- animals 		******************************************/
{level:"3", theme: "animals", question: "What is JavaScript?", answers: ["client-side scripting language", "son of java", "father of python", "language"], correct: 1},
{level:"3", theme: "animals", question: "What is the purpose of minifying the JavaScript?", answers: ["To streamline the visits", "To save the visits", "Both a and b", "None of the mentioned"], correct: 1},
{level:"3", theme: "animals", question: "From which did Minification concept originate?", answers: ["JavaScript code efficiency", "JavaScript interpreter", "Both a and b", "None of the mentioned"], correct: 2},
{level:"3", theme: "animals", question: "What is the purpose of the product Minify?", answers: ["Storing the data", "Streamlining the data", "Proxies the JavaScript file", "All of the mentioned"], correct: 3},
{level:"3", theme: "animals", question: "What does the Minify set the encoding HTTP header?", answers: ["deflate", "gzip", "Both a and b", "None of the mentioned"], correct: 3},
{level:"3", theme: "animals", question: "What is in-built in the Minify?", answers: ["Dynamic compression", "Static compression", "Static content", "None of the mentioned"], correct: 2},
{level:"3", theme: "animals", question: "YUI Compressor is analogous to", answers: ["Minify", "JavaScript", "Both a and b", "None of the mentioned"], correct: 1},
/****************************************** 		level 4 ----------- animals 		******************************************/
{level:"4", theme: "animals", question: "What is JavaScript?", answers: ["client-side scripting language", "son of java", "father of python", "language"], correct: 1},
{level:"4", theme: "animals", question: "What is the purpose of minifying the JavaScript?", answers: ["To streamline the visits", "To save the visits", "Both a and b", "None of the mentioned"], correct: 1},
{level:"4", theme: "animals", question: "From which did Minification concept originate?", answers: ["JavaScript code efficiency", "JavaScript interpreter", "Both a and b", "None of the mentioned"], correct: 2},
{level:"4", theme: "animals", question: "What is the purpose of the product Minify?", answers: ["Storing the data", "Streamlining the data", "Proxies the JavaScript file", "All of the mentioned"], correct: 3},
{level:"4", theme: "animals", question: "What does the Minify set the encoding HTTP header?", answers: ["deflate", "gzip", "Both a and b", "None of the mentioned"], correct: 3},
{level:"4", theme: "animals", question: "What is in-built in the Minify?", answers: ["Dynamic compression", "Static compression", "Static content", "None of the mentioned"], correct: 2},
{level:"4", theme: "animals", question: "YUI Compressor is analogous to", answers: ["Minify", "JavaScript", "Both a and b", "None of the mentioned"], correct: 1},
/****************************************** 		level 5 ----------- animals 		******************************************/
{level:"5", theme: "animals", question: "What is JavaScript?", answers: ["client-side scripting language", "son of java", "father of python", "language"], correct: 1},
{level:"5", theme: "animals", question: "What is the purpose of minifying the JavaScript?", answers: ["To streamline the visits", "To save the visits", "Both a and b", "None of the mentioned"], correct: 1},
{level:"5", theme: "animals", question: "From which did Minification concept originate?", answers: ["JavaScript code efficiency", "JavaScript interpreter", "Both a and b", "None of the mentioned"], correct: 2},
{level:"5", theme: "animals", question: "What is the purpose of the product Minify?", answers: ["Storing the data", "Streamlining the data", "Proxies the JavaScript file", "All of the mentioned"], correct: 3},
{level:"5", theme: "animals", question: "What does the Minify set the encoding HTTP header?", answers: ["deflate", "gzip", "Both a and b", "None of the mentioned"], correct: 3},
{level:"5", theme: "animals", question: "What is in-built in the Minify?", answers: ["Dynamic compression", "Static compression", "Static content", "None of the mentioned"], correct: 2},
{level:"5", theme: "animals", question: "YUI Compressor is analogous to", answers: ["Minify", "JavaScript", "Both a and b", "None of the mentioned"], correct: 1},

/****************************************** 		level 1 ----------- plants 		******************************************/
{level:"1", theme: "plants", question: "What is JavaScript?", answers: ["client-side scripting language", "son of java", "father of python", "language"], correct: 1},
{level:"1", theme: "plants", question: "What is the purpose of minifying the JavaScript?", answers: ["To streamline the visits", "To save the visits", "Both a and b", "None of the mentioned"], correct: 1},
{level:"1", theme: "plants", question: "From which did Minification concept originate?", answers: ["JavaScript code efficiency", "JavaScript interpreter", "Both a and b", "None of the mentioned"], correct: 2},
{level:"1", theme: "plants", question: "What is the purpose of the product Minify?", answers: ["Storing the data", "Streamlining the data", "Proxies the JavaScript file", "All of the mentioned"], correct: 3},
{level:"1", theme: "plants", question: "What does the Minify set the encoding HTTP header?", answers: ["deflate", "gzip", "Both a and b", "None of the mentioned"], correct: 3},
{level:"1", theme: "plants", question: "What is in-built in the Minify?", answers: ["Dynamic compression", "Static compression", "Static content", "None of the mentioned"], correct: 2},
{level:"1", theme: "plants", question: "YUI Compressor is analogous to", answers: ["Minify", "JavaScript", "Both a and b", "None of the mentioned"], correct: 1},
/****************************************** 		level 2 ----------- plants 		******************************************/
{level:"2", theme: "plants", question: "What is JavaScript?", answers: ["client-side scripting language", "son of java", "father of python", "language"], correct: 1},
{level:"2", theme: "plants", question: "What is the purpose of minifying the JavaScript?", answers: ["To streamline the visits", "To save the visits", "Both a and b", "None of the mentioned"], correct: 1},
{level:"2", theme: "plants", question: "From which did Minification concept originate?", answers: ["JavaScript code efficiency", "JavaScript interpreter", "Both a and b", "None of the mentioned"], correct: 2},
{level:"2", theme: "plants", question: "What is the purpose of the product Minify?", answers: ["Storing the data", "Streamlining the data", "Proxies the JavaScript file", "All of the mentioned"], correct: 3},
{level:"2", theme: "plants", question: "What does the Minify set the encoding HTTP header?", answers: ["deflate", "gzip", "Both a and b", "None of the mentioned"], correct: 3},
{level:"2", theme: "plants", question: "What is in-built in the Minify?", answers: ["Dynamic compression", "Static compression", "Static content", "None of the mentioned"], correct: 2},
{level:"2", theme: "plants", question: "YUI Compressor is analogous to", answers: ["Minify", "JavaScript", "Both a and b", "None of the mentioned"], correct: 1},
/****************************************** 		level 3 ----------- plants 		******************************************/
{level:"3", theme: "plants", question: "What is JavaScript?", answers: ["client-side scripting language", "son of java", "father of python", "language"], correct: 1},
{level:"3", theme: "plants", question: "What is the purpose of minifying the JavaScript?", answers: ["To streamline the visits", "To save the visits", "Both a and b", "None of the mentioned"], correct: 1},
{level:"3", theme: "plants", question: "From which did Minification concept originate?", answers: ["JavaScript code efficiency", "JavaScript interpreter", "Both a and b", "None of the mentioned"], correct: 2},
{level:"3", theme: "plants", question: "What is the purpose of the product Minify?", answers: ["Storing the data", "Streamlining the data", "Proxies the JavaScript file", "All of the mentioned"], correct: 3},
{level:"3", theme: "plants", question: "What does the Minify set the encoding HTTP header?", answers: ["deflate", "gzip", "Both a and b", "None of the mentioned"], correct: 3},
{level:"3", theme: "plants", question: "What is in-built in the Minify?", answers: ["Dynamic compression", "Static compression", "Static content", "None of the mentioned"], correct: 2},
{level:"3", theme: "plants", question: "YUI Compressor is analogous to", answers: ["Minify", "JavaScript", "Both a and b", "None of the mentioned"], correct: 1},
/****************************************** 		level 4 ----------- plants 		******************************************/
{level:"4", theme: "plants", question: "What is JavaScript?", answers: ["client-side scripting language", "son of java", "father of python", "language"], correct: 1},
{level:"4", theme: "plants", question: "What is the purpose of minifying the JavaScript?", answers: ["To streamline the visits", "To save the visits", "Both a and b", "None of the mentioned"], correct: 1},
{level:"4", theme: "plants", question: "From which did Minification concept originate?", answers: ["JavaScript code efficiency", "JavaScript interpreter", "Both a and b", "None of the mentioned"], correct: 2},
{level:"4", theme: "plants", question: "What is the purpose of the product Minify?", answers: ["Storing the data", "Streamlining the data", "Proxies the JavaScript file", "All of the mentioned"], correct: 3},
{level:"4", theme: "plants", question: "What does the Minify set the encoding HTTP header?", answers: ["deflate", "gzip", "Both a and b", "None of the mentioned"], correct: 3},
{level:"4", theme: "plants", question: "What is in-built in the Minify?", answers: ["Dynamic compression", "Static compression", "Static content", "None of the mentioned"], correct: 2},
{level:"4", theme: "plants", question: "YUI Compressor is analogous to", answers: ["Minify", "JavaScript", "Both a and b", "None of the mentioned"], correct: 1},
/****************************************** 		level 5 ----------- plants 		******************************************/
{level:"5", theme: "plants", question: "What is JavaScript?", answers: ["client-side scripting language", "son of java", "father of python", "language"], correct: 1},
{level:"5", theme: "plants", question: "What is the purpose of minifying the JavaScript?", answers: ["To streamline the visits", "To save the visits", "Both a and b", "None of the mentioned"], correct: 1},
{level:"5", theme: "plants", question: "From which did Minification concept originate?", answers: ["JavaScript code efficiency", "JavaScript interpreter", "Both a and b", "None of the mentioned"], correct: 2},
{level:"5", theme: "plants", question: "What is the purpose of the product Minify?", answers: ["Storing the data", "Streamlining the data", "Proxies the JavaScript file", "All of the mentioned"], correct: 3},
{level:"5", theme: "plants", question: "What does the Minify set the encoding HTTP header?", answers: ["deflate", "gzip", "Both a and b", "None of the mentioned"], correct: 3},
{level:"5", theme: "plants", question: "What is in-built in the Minify?", answers: ["Dynamic compression", "Static compression", "Static content", "None of the mentioned"], correct: 2},
{level:"5", theme: "plants", question: "YUI Compressor is analogous to", answers: ["Minify", "JavaScript", "Both a and b", "None of the mentioned"], correct: 1},


/****************************************** 		level 1 ----------- water 		******************************************/
{level:"1", theme: "water", question: "What is JavaScript?", answers: ["client-side scripting language", "son of java", "father of python", "language"], correct: 1},
{level:"1", theme: "water", question: "What is the purpose of minifying the JavaScript?", answers: ["To streamline the visits", "To save the visits", "Both a and b", "None of the mentioned"], correct: 1},
{level:"1", theme: "water", question: "From which did Minification concept originate?", answers: ["JavaScript code efficiency", "JavaScript interpreter", "Both a and b", "None of the mentioned"], correct: 2},
{level:"1", theme: "water", question: "What is the purpose of the product Minify?", answers: ["Storing the data", "Streamlining the data", "Proxies the JavaScript file", "All of the mentioned"], correct: 3},
{level:"1", theme: "water", question: "What does the Minify set the encoding HTTP header?", answers: ["deflate", "gzip", "Both a and b", "None of the mentioned"], correct: 3},
{level:"1", theme: "water", question: "What is in-built in the Minify?", answers: ["Dynamic compression", "Static compression", "Static content", "None of the mentioned"], correct: 2},
{level:"1", theme: "water", question: "YUI Compressor is analogous to", answers: ["Minify", "JavaScript", "Both a and b", "None of the mentioned"], correct: 1},
/****************************************** 		level 2 ----------- water 		******************************************/
{level:"2", theme: "water", question: "What is JavaScript?", answers: ["client-side scripting language", "son of java", "father of python", "language"], correct: 1},
{level:"2", theme: "water", question: "What is the purpose of minifying the JavaScript?", answers: ["To streamline the visits", "To save the visits", "Both a and b", "None of the mentioned"], correct: 1},
{level:"2", theme: "water", question: "From which did Minification concept originate?", answers: ["JavaScript code efficiency", "JavaScript interpreter", "Both a and b", "None of the mentioned"], correct: 2},
{level:"2", theme: "water", question: "What is the purpose of the product Minify?", answers: ["Storing the data", "Streamlining the data", "Proxies the JavaScript file", "All of the mentioned"], correct: 3},
{level:"2", theme: "water", question: "What does the Minify set the encoding HTTP header?", answers: ["deflate", "gzip", "Both a and b", "None of the mentioned"], correct: 3},
{level:"2", theme: "water", question: "What is in-built in the Minify?", answers: ["Dynamic compression", "Static compression", "Static content", "None of the mentioned"], correct: 2},
{level:"2", theme: "water", question: "YUI Compressor is analogous to", answers: ["Minify", "JavaScript", "Both a and b", "None of the mentioned"], correct: 1},
/****************************************** 		level 3 ----------- water 		******************************************/
{level:"3", theme: "water", question: "What is JavaScript?", answers: ["client-side scripting language", "son of java", "father of python", "language"], correct: 1},
{level:"3", theme: "water", question: "What is the purpose of minifying the JavaScript?", answers: ["To streamline the visits", "To save the visits", "Both a and b", "None of the mentioned"], correct: 1},
{level:"3", theme: "water", question: "From which did Minification concept originate?", answers: ["JavaScript code efficiency", "JavaScript interpreter", "Both a and b", "None of the mentioned"], correct: 2},
{level:"3", theme: "water", question: "What is the purpose of the product Minify?", answers: ["Storing the data", "Streamlining the data", "Proxies the JavaScript file", "All of the mentioned"], correct: 3},
{level:"3", theme: "water", question: "What does the Minify set the encoding HTTP header?", answers: ["deflate", "gzip", "Both a and b", "None of the mentioned"], correct: 3},
{level:"3", theme: "water", question: "What is in-built in the Minify?", answers: ["Dynamic compression", "Static compression", "Static content", "None of the mentioned"], correct: 2},
{level:"3", theme: "water", question: "YUI Compressor is analogous to", answers: ["Minify", "JavaScript", "Both a and b", "None of the mentioned"], correct: 1},
/****************************************** 		level 4 ----------- water 		******************************************/
{level:"4", theme: "water", question: "What is JavaScript?", answers: ["client-side scripting language", "son of java", "father of python", "language"], correct: 1},
{level:"4", theme: "water", question: "What is the purpose of minifying the JavaScript?", answers: ["To streamline the visits", "To save the visits", "Both a and b", "None of the mentioned"], correct: 1},
{level:"4", theme: "water", question: "From which did Minification concept originate?", answers: ["JavaScript code efficiency", "JavaScript interpreter", "Both a and b", "None of the mentioned"], correct: 2},
{level:"4", theme: "water", question: "What is the purpose of the product Minify?", answers: ["Storing the data", "Streamlining the data", "Proxies the JavaScript file", "All of the mentioned"], correct: 3},
{level:"4", theme: "water", question: "What does the Minify set the encoding HTTP header?", answers: ["deflate", "gzip", "Both a and b", "None of the mentioned"], correct: 3},
{level:"4", theme: "water", question: "What is in-built in the Minify?", answers: ["Dynamic compression", "Static compression", "Static content", "None of the mentioned"], correct: 2},
{level:"4", theme: "water", question: "YUI Compressor is analogous to", answers: ["Minify", "JavaScript", "Both a and b", "None of the mentioned"], correct: 1},
/****************************************** 		level 5 ----------- water 		******************************************/
{level:"5", theme: "water", question: "What is JavaScript?", answers: ["client-side scripting language", "son of java", "father of python", "language"], correct: 1},
{level:"5", theme: "water", question: "What is the purpose of minifying the JavaScript?", answers: ["To streamline the visits", "To save the visits", "Both a and b", "None of the mentioned"], correct: 1},
{level:"5", theme: "water", question: "From which did Minification concept originate?", answers: ["JavaScript code efficiency", "JavaScript interpreter", "Both a and b", "None of the mentioned"], correct: 2},
{level:"5", theme: "water", question: "What is the purpose of the product Minify?", answers: ["Storing the data", "Streamlining the data", "Proxies the JavaScript file", "All of the mentioned"], correct: 3},
{level:"5", theme: "water", question: "What does the Minify set the encoding HTTP header?", answers: ["deflate", "gzip", "Both a and b", "None of the mentioned"], correct: 3},
{level:"5", theme: "water", question: "What is in-built in the Minify?", answers: ["Dynamic compression", "Static compression", "Static content", "None of the mentioned"], correct: 2},
{level:"5", theme: "water", question: "YUI Compressor is analogous to", answers: ["Minify", "JavaScript", "Both a and b", "None of the mentioned"], correct: 1},


/****************************************** 		level 1 ----------- safety 		******************************************/
{level:"1", theme: "safety", question: "What is JavaScript?", answers: ["client-side scripting language", "son of java", "father of python", "language"], correct: 1},
{level:"1", theme: "safety", question: "What is the purpose of minifying the JavaScript?", answers: ["To streamline the visits", "To save the visits", "Both a and b", "None of the mentioned"], correct: 1},
{level:"1", theme: "safety", question: "From which did Minification concept originate?", answers: ["JavaScript code efficiency", "JavaScript interpreter", "Both a and b", "None of the mentioned"], correct: 2},
{level:"1", theme: "safety", question: "What is the purpose of the product Minify?", answers: ["Storing the data", "Streamlining the data", "Proxies the JavaScript file", "All of the mentioned"], correct: 3},
{level:"1", theme: "safety", question: "What does the Minify set the encoding HTTP header?", answers: ["deflate", "gzip", "Both a and b", "None of the mentioned"], correct: 3},
{level:"1", theme: "safety", question: "What is in-built in the Minify?", answers: ["Dynamic compression", "Static compression", "Static content", "None of the mentioned"], correct: 2},
{level:"1", theme: "safety", question: "YUI Compressor is analogous to", answers: ["Minify", "JavaScript", "Both a and b", "None of the mentioned"], correct: 1},
/****************************************** 		level 2 ----------- safety 		******************************************/
{level:"2", theme: "safety", question: "What is JavaScript?", answers: ["client-side scripting language", "son of java", "father of python", "language"], correct: 1},
{level:"2", theme: "safety", question: "What is the purpose of minifying the JavaScript?", answers: ["To streamline the visits", "To save the visits", "Both a and b", "None of the mentioned"], correct: 1},
{level:"2", theme: "safety", question: "From which did Minification concept originate?", answers: ["JavaScript code efficiency", "JavaScript interpreter", "Both a and b", "None of the mentioned"], correct: 2},
{level:"2", theme: "safety", question: "What is the purpose of the product Minify?", answers: ["Storing the data", "Streamlining the data", "Proxies the JavaScript file", "All of the mentioned"], correct: 3},
{level:"2", theme: "safety", question: "What does the Minify set the encoding HTTP header?", answers: ["deflate", "gzip", "Both a and b", "None of the mentioned"], correct: 3},
{level:"2", theme: "safety", question: "What is in-built in the Minify?", answers: ["Dynamic compression", "Static compression", "Static content", "None of the mentioned"], correct: 2},
{level:"2", theme: "safety", question: "YUI Compressor is analogous to", answers: ["Minify", "JavaScript", "Both a and b", "None of the mentioned"], correct: 1},
/****************************************** 		level 3 ----------- safety 		******************************************/
{level:"3", theme: "safety", question: "What is JavaScript?", answers: ["client-side scripting language", "son of java", "father of python", "language"], correct: 1},
{level:"3", theme: "safety", question: "What is the purpose of minifying the JavaScript?", answers: ["To streamline the visits", "To save the visits", "Both a and b", "None of the mentioned"], correct: 1},
{level:"3", theme: "safety", question: "From which did Minification concept originate?", answers: ["JavaScript code efficiency", "JavaScript interpreter", "Both a and b", "None of the mentioned"], correct: 2},
{level:"3", theme: "safety", question: "What is the purpose of the product Minify?", answers: ["Storing the data", "Streamlining the data", "Proxies the JavaScript file", "All of the mentioned"], correct: 3},
{level:"3", theme: "safety", question: "What does the Minify set the encoding HTTP header?", answers: ["deflate", "gzip", "Both a and b", "None of the mentioned"], correct: 3},
{level:"3", theme: "safety", question: "What is in-built in the Minify?", answers: ["Dynamic compression", "Static compression", "Static content", "None of the mentioned"], correct: 2},
{level:"3", theme: "safety", question: "YUI Compressor is analogous to", answers: ["Minify", "JavaScript", "Both a and b", "None of the mentioned"], correct: 1},
/****************************************** 		level 4 ----------- safety 		******************************************/
{level:"4", theme: "safety", question: "What is JavaScript?", answers: ["client-side scripting language", "son of java", "father of python", "language"], correct: 1},
{level:"4", theme: "safety", question: "What is the purpose of minifying the JavaScript?", answers: ["To streamline the visits", "To save the visits", "Both a and b", "None of the mentioned"], correct: 1},
{level:"4", theme: "safety", question: "From which did Minification concept originate?", answers: ["JavaScript code efficiency", "JavaScript interpreter", "Both a and b", "None of the mentioned"], correct: 2},
{level:"4", theme: "safety", question: "What is the purpose of the product Minify?", answers: ["Storing the data", "Streamlining the data", "Proxies the JavaScript file", "All of the mentioned"], correct: 3},
{level:"4", theme: "safety", question: "What does the Minify set the encoding HTTP header?", answers: ["deflate", "gzip", "Both a and b", "None of the mentioned"], correct: 3},
{level:"4", theme: "safety", question: "What is in-built in the Minify?", answers: ["Dynamic compression", "Static compression", "Static content", "None of the mentioned"], correct: 2},
{level:"4", theme: "safety", question: "YUI Compressor is analogous to", answers: ["Minify", "JavaScript", "Both a and b", "None of the mentioned"], correct: 1},
/****************************************** 		level 5 ----------- safety 		******************************************/
{level:"5", theme: "safety", question: "What is JavaScript?", answers: ["client-side scripting language", "son of java", "father of python", "language"], correct: 1},
{level:"5", theme: "safety", question: "What is the purpose of minifying the JavaScript?", answers: ["To streamline the visits", "To save the visits", "Both a and b", "None of the mentioned"], correct: 1},
{level:"5", theme: "safety", question: "From which did Minification concept originate?", answers: ["JavaScript code efficiency", "JavaScript interpreter", "Both a and b", "None of the mentioned"], correct: 2},
{level:"5", theme: "safety", question: "What is the purpose of the product Minify?", answers: ["Storing the data", "Streamlining the data", "Proxies the JavaScript file", "All of the mentioned"], correct: 3},
{level:"5", theme: "safety", question: "What does the Minify set the encoding HTTP header?", answers: ["deflate", "gzip", "Both a and b", "None of the mentioned"], correct: 3},
{level:"5", theme: "safety", question: "What is in-built in the Minify?", answers: ["Dynamic compression", "Static compression", "Static content", "None of the mentioned"], correct: 2},
{level:"5", theme: "safety", question: "YUI Compressor is analogous to", answers: ["Minify", "JavaScript", "Both a and b", "None of the mentioned"], correct: 1},



/****************************************** 		level 1 ----------- food 		******************************************/
{level:"1", theme: "food", question: "What is JavaScript?", answers: ["client-side scripting language", "son of java", "father of python", "language"], correct: 1},
{level:"1", theme: "food", question: "What is the purpose of minifying the JavaScript?", answers: ["To streamline the visits", "To save the visits", "Both a and b", "None of the mentioned"], correct: 1},
{level:"1", theme: "food", question: "From which did Minification concept originate?", answers: ["JavaScript code efficiency", "JavaScript interpreter", "Both a and b", "None of the mentioned"], correct: 2},
{level:"1", theme: "food", question: "What is the purpose of the product Minify?", answers: ["Storing the data", "Streamlining the data", "Proxies the JavaScript file", "All of the mentioned"], correct: 3},
{level:"1", theme: "food", question: "What does the Minify set the encoding HTTP header?", answers: ["deflate", "gzip", "Both a and b", "None of the mentioned"], correct: 3},
{level:"1", theme: "food", question: "What is in-built in the Minify?", answers: ["Dynamic compression", "Static compression", "Static content", "None of the mentioned"], correct: 2},
{level:"1", theme: "food", question: "YUI Compressor is analogous to", answers: ["Minify", "JavaScript", "Both a and b", "None of the mentioned"], correct: 1},
/****************************************** 		level 2 ----------- food 		******************************************/
{level:"2", theme: "food", question: "What is JavaScript?", answers: ["client-side scripting language", "son of java", "father of python", "language"], correct: 1},
{level:"2", theme: "food", question: "What is the purpose of minifying the JavaScript?", answers: ["To streamline the visits", "To save the visits", "Both a and b", "None of the mentioned"], correct: 1},
{level:"2", theme: "food", question: "From which did Minification concept originate?", answers: ["JavaScript code efficiency", "JavaScript interpreter", "Both a and b", "None of the mentioned"], correct: 2},
{level:"2", theme: "food", question: "What is the purpose of the product Minify?", answers: ["Storing the data", "Streamlining the data", "Proxies the JavaScript file", "All of the mentioned"], correct: 3},
{level:"2", theme: "food", question: "What does the Minify set the encoding HTTP header?", answers: ["deflate", "gzip", "Both a and b", "None of the mentioned"], correct: 3},
{level:"2", theme: "food", question: "What is in-built in the Minify?", answers: ["Dynamic compression", "Static compression", "Static content", "None of the mentioned"], correct: 2},
{level:"2", theme: "food", question: "YUI Compressor is analogous to", answers: ["Minify", "JavaScript", "Both a and b", "None of the mentioned"], correct: 1},
/****************************************** 		level 3 ----------- food 		******************************************/
{level:"3", theme: "food", question: "What is JavaScript?", answers: ["client-side scripting language", "son of java", "father of python", "language"], correct: 1},
{level:"3", theme: "food", question: "What is the purpose of minifying the JavaScript?", answers: ["To streamline the visits", "To save the visits", "Both a and b", "None of the mentioned"], correct: 1},
{level:"3", theme: "food", question: "From which did Minification concept originate?", answers: ["JavaScript code efficiency", "JavaScript interpreter", "Both a and b", "None of the mentioned"], correct: 2},
{level:"3", theme: "food", question: "What is the purpose of the product Minify?", answers: ["Storing the data", "Streamlining the data", "Proxies the JavaScript file", "All of the mentioned"], correct: 3},
{level:"3", theme: "food", question: "What does the Minify set the encoding HTTP header?", answers: ["deflate", "gzip", "Both a and b", "None of the mentioned"], correct: 3},
{level:"3", theme: "food", question: "What is in-built in the Minify?", answers: ["Dynamic compression", "Static compression", "Static content", "None of the mentioned"], correct: 2},
{level:"3", theme: "food", question: "YUI Compressor is analogous to", answers: ["Minify", "JavaScript", "Both a and b", "None of the mentioned"], correct: 1},
/****************************************** 		level 4 ----------- food 		******************************************/
{level:"4", theme: "food", question: "What is JavaScript?", answers: ["client-side scripting language", "son of java", "father of python", "language"], correct: 1},
{level:"4", theme: "food", question: "What is the purpose of minifying the JavaScript?", answers: ["To streamline the visits", "To save the visits", "Both a and b", "None of the mentioned"], correct: 1},
{level:"4", theme: "food", question: "From which did Minification concept originate?", answers: ["JavaScript code efficiency", "JavaScript interpreter", "Both a and b", "None of the mentioned"], correct: 2},
{level:"4", theme: "food", question: "What is the purpose of the product Minify?", answers: ["Storing the data", "Streamlining the data", "Proxies the JavaScript file", "All of the mentioned"], correct: 3},
{level:"4", theme: "food", question: "What does the Minify set the encoding HTTP header?", answers: ["deflate", "gzip", "Both a and b", "None of the mentioned"], correct: 3},
{level:"4", theme: "food", question: "What is in-built in the Minify?", answers: ["Dynamic compression", "Static compression", "Static content", "None of the mentioned"], correct: 2},
{level:"4", theme: "food", question: "YUI Compressor is analogous to", answers: ["Minify", "JavaScript", "Both a and b", "None of the mentioned"], correct: 1},
/****************************************** 		level 5 ----------- food 		******************************************/
{level:"5", theme: "food", question: "What is JavaScript?", answers: ["client-side scripting language", "son of java", "father of python", "language"], correct: 1},
{level:"5", theme: "food", question: "What is the purpose of minifying the JavaScript?", answers: ["To streamline the visits", "To save the visits", "Both a and b", "None of the mentioned"], correct: 1},
{level:"5", theme: "food", question: "From which did Minification concept originate?", answers: ["JavaScript code efficiency", "JavaScript interpreter", "Both a and b", "None of the mentioned"], correct: 2},
{level:"5", theme: "food", question: "What is the purpose of the product Minify?", answers: ["Storing the data", "Streamlining the data", "Proxies the JavaScript file", "All of the mentioned"], correct: 3},
{level:"5", theme: "food", question: "What does the Minify set the encoding HTTP header?", answers: ["deflate", "gzip", "Both a and b", "None of the mentioned"], correct: 3},
{level:"5", theme: "food", question: "What is in-built in the Minify?", answers: ["Dynamic compression", "Static compression", "Static content", "None of the mentioned"], correct: 2},
{level:"5", theme: "food", question: "YUI Compressor is analogous to", answers: ["Minify", "JavaScript", "Both a and b", "None of the mentioned"], correct: 1},

];